# Generated by Django 3.2.9 on 2021-11-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Наименование трека')),
                ('artist', models.CharField(max_length=90, verbose_name='Исполнитель')),
                ('image', models.ImageField(upload_to='', verbose_name='Обложка трека')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
                ('audio_link', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.TextField(max_length=2000, null=True, verbose_name='Текст песни')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
