# Generated by Django 3.2.9 on 2021-11-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_link',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AlterField(
            model_name='song',
            name='text',
            field=models.TextField(max_length=50000, null=True, verbose_name='Текст песни'),
        ),
    ]
