# Generated by Django 3.2.9 on 2021-11-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20211114_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='textHTML',
            field=models.TextField(max_length=10000, null=True, verbose_name='Текст песни с HTML треками'),
        ),
    ]
