# Generated by Django 3.2.9 on 2021-11-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_song_texthtml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='textHTML',
            field=models.TextField(max_length=10000, null=True, verbose_name='Текст песни с HTML тэгами'),
        ),
    ]
