# Generated by Django 3.2.9 on 2021-11-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='text',
            field=models.TextField(max_length=2000, null=True, verbose_name='Текст песни'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=90, verbose_name='Исполнитель'),
        ),
    ]
