# Generated by Django 3.2.9 on 2021-11-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_song_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
