# Generated by Django 3.2.9 on 2021-11-29 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0007_song_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загружающее лицо'),
        ),
        migrations.AlterField(
            model_name='like',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.song', verbose_name='Аудиотрек'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Аудио файл'),
        ),
        migrations.AlterField(
            model_name='song',
            name='created',
            field=models.TimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='song',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Верицирован'),
        ),
    ]
