# Generated by Django 3.2.9 on 2021-11-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.TextField(max_length=90, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Обложка трека'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=90, verbose_name='Наименование трека'),
        ),
    ]
