# Generated by Django 3.2.9 on 2021-11-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=3000)),
                ('message_html', models.TextField(max_length=3000, null=True, verbose_name='Описание сообщение в виде html страницы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания сообщения')),
                ('room_name', models.CharField(default='no room', max_length=100, verbose_name='Наменование команты чата')),
            ],
        ),
    ]
