# Generated by Django 3.2.9 on 2021-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='updated',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room_name',
            field=models.CharField(default='no room', max_length=100, verbose_name='Наменование команты чата'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания сообщения'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_html',
            field=models.TextField(max_length=3000, null=True, verbose_name='Описание сообщение в виде html страницы'),
        ),
    ]
