# Generated by Django 3.2.9 on 2021-11-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='message_html',
        ),
    ]
