# Generated by Django 3.2.9 on 2021-11-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
